apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemmygo-user
  namespace: lemmygo
  labels:
    app: lemmygo-users
spec:
  replicas: 1
  template:
    metadata:
      name: lemmygo-users
      labels:
        app: lemmygo-users
    spec:
      containers:
        - name: lemmygo-users
          image: registry.gitlab.com/lemmygo/lemmygo-users:latest
          ports:
            - containerPort: 8081
          env:
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongourl
                  key: mongourl
        - name: lemmygo-envoy
          image: registry.gitlab.com/lemmygo/lemmygo-envoy
      imagePullSecrets:
        - name: regcred
  selector:
    matchLabels:
      app: lemmygo-users
---
apiVersion: v1
kind: Service
metadata:
  name: lemmygo-users-service
  namespace: lemmygo
  labels:
    app: lemmygo-users
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30808
  selector:
    app: lemmygo-users
